set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(TOOLCHAIN_PREFIX avr-)

find_program(AVR_GCC avr-gcc REQUIRED)
get_filename_component(BINUTILS_PATH "${AVR_GCC}" DIRECTORY)

set(CMAKE_C_COMPILER   "${BINUTILS_PATH}/avr-gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${BINUTILS_PATH}/avr-g++" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${BINUTILS_PATH}/avr-gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_AR           "${BINUTILS_PATH}/avr-gcc-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB       "${BINUTILS_PATH}/avr-gcc-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY      "${BINUTILS_PATH}/avr-objcopy" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP      "${BINUTILS_PATH}/avr-objdump" CACHE FILEPATH "" FORCE)
set(CMAKE_SIZE_UTIL    "${BINUTILS_PATH}/avr-size" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
